---
- name: check httpd status
  hosts: web
  tasks:
  - name: check_httpd
    ansible.builtin.shell:
      cmd: systemctl status httpd
    register: result


  - name: Display result
    debug: 
      msg: "{{result.stdout_lines}}"
