---
- name: web 
  become: yes
  become_method: sudo 
  tasks: 

  - name: Install httpd 
    yum: 
     name: httpd 
     state: latest 
     update_cache: yes 
  when: ansible_facts['os_family'] == "RHEL"

  - name: start httpd
    service: 
      name: httpd 
      state: started
  when: ansible_facts['os_family'] == "RHEL"
  